# Generated by Django 6.0.7 on 2026-07-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionstep',
            name='description',
            field=models.CharField(help_text='Human-readable narration of this step, e.g. "Selected tool: CalculatorTool".', max_length=255),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='step_number',
            field=models.PositiveIntegerField(help_text="1-indexed position of this step within the task's execution trace."),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='tool_name',
            field=models.CharField(blank=True, help_text='Tool that produced this step; null on bookkeeping steps (received input / returning result).', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='prompt',
            field=models.TextField(help_text='Natural-language instruction for the agent, e.g. "What is 15 + 27?".'),
        ),
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.TextField(blank=True, default='', help_text="Agent's final output. Read-only — populated by tool execution, not set by the client."),
        ),
    ]
